--
-- PostgreSQL database dump
--

\restrict GrKPmnWU0Fzd7QSncVBZFEMghdvRtUbwoSy0m4uu4f4YnZVZwDaTv5HNBAajC1e

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

-- Started on 2026-06-25 16:05:44

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16490)
-- Name: department; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.department (
    id bigint NOT NULL,
    code character varying(50),
    name character varying(255),
    created_by bigint,
    updated_by bigint
);


ALTER TABLE public.department OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16489)
-- Name: department_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16568)
-- Name: dish; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dish (
    id bigint NOT NULL,
    name character varying(255),
    description text,
    is_active boolean DEFAULT true,
    created_by bigint,
    updated_by bigint
);


ALTER TABLE public.dish OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16567)
-- Name: dish_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dish ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dish_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16690)
-- Name: invalidated_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invalidated_token (
    id bigint NOT NULL,
    token character varying(500),
    expiry_time timestamp with time zone
);


ALTER TABLE public.invalidated_token OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16689)
-- Name: invalidated_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invalidated_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invalidated_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16577)
-- Name: menu; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.menu (
    id bigint NOT NULL,
    menu_date date,
    price numeric(10,2),
    is_special boolean DEFAULT false,
    status character varying(20),
    created_by bigint,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint
);


ALTER TABLE public.menu OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16591)
-- Name: menu_dish; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.menu_dish (
    menu_id bigint NOT NULL,
    dish_id bigint NOT NULL
);


ALTER TABLE public.menu_dish OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16576)
-- Name: menu_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.menu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16674)
-- Name: notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notification (
    id bigint NOT NULL,
    user_id bigint,
    title character varying(255),
    content text,
    is_read boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.notification OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16673)
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16607)
-- Name: order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."order" (
    id bigint NOT NULL,
    user_id bigint,
    menu_id bigint,
    price numeric(10,2),
    status character varying(20),
    ticket_source character varying(10),
    original_user_id bigint,
    is_printed boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint
);


ALTER TABLE public."order" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16606)
-- Name: order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."order" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16506)
-- Name: permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permission (
    id bigint NOT NULL,
    action character varying(100),
    description character varying(255),
    created_by bigint,
    updated_by bigint
);


ALTER TABLE public.permission OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16505)
-- Name: permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16654)
-- Name: rating; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rating (
    id bigint NOT NULL,
    user_id bigint,
    menu_id bigint,
    score integer,
    comment text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rating_score_check CHECK (((score >= 1) AND (score <= 5)))
);


ALTER TABLE public.rating OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16653)
-- Name: rating_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rating ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rating_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16700)
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_token (
    id bigint NOT NULL,
    user_id bigint,
    token character varying(500),
    expiry_time timestamp with time zone
);


ALTER TABLE public.refresh_token OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 16699)
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16498)
-- Name: role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role (
    id bigint NOT NULL,
    code character varying(50),
    name character varying(255),
    created_by bigint,
    updated_by bigint
);


ALTER TABLE public.role OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16497)
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16552)
-- Name: role_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role_permission (
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL
);


ALTER TABLE public.role_permission OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16634)
-- Name: ticket_exchange; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ticket_exchange (
    id bigint NOT NULL,
    order_id bigint,
    buyer_id bigint,
    status character varying(20),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.ticket_exchange OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16633)
-- Name: ticket_exchange_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ticket_exchange ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_exchange_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16514)
-- Name: user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."user" (
    id bigint NOT NULL,
    username character varying(50),
    employee_code character varying(50),
    full_name character varying(255),
    email character varying(255),
    password character varying(255),
    department_id bigint,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_by bigint
);


ALTER TABLE public."user" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16513)
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16537)
-- Name: user_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_role (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.user_role OWNER TO postgres;

--
-- TOC entry 5048 (class 0 OID 16490)
-- Dependencies: 216
-- Data for Name: department; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5058 (class 0 OID 16568)
-- Dependencies: 226
-- Data for Name: dish; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5071 (class 0 OID 16690)
-- Dependencies: 239
-- Data for Name: invalidated_token; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5060 (class 0 OID 16577)
-- Dependencies: 228
-- Data for Name: menu; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5061 (class 0 OID 16591)
-- Dependencies: 229
-- Data for Name: menu_dish; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5069 (class 0 OID 16674)
-- Dependencies: 237
-- Data for Name: notification; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5063 (class 0 OID 16607)
-- Dependencies: 231
-- Data for Name: order; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5052 (class 0 OID 16506)
-- Dependencies: 220
-- Data for Name: permission; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5067 (class 0 OID 16654)
-- Dependencies: 235
-- Data for Name: rating; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5073 (class 0 OID 16700)
-- Dependencies: 241
-- Data for Name: refresh_token; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5050 (class 0 OID 16498)
-- Dependencies: 218
-- Data for Name: role; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5056 (class 0 OID 16552)
-- Dependencies: 224
-- Data for Name: role_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5065 (class 0 OID 16634)
-- Dependencies: 233
-- Data for Name: ticket_exchange; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5054 (class 0 OID 16514)
-- Dependencies: 222
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5055 (class 0 OID 16537)
-- Dependencies: 223
-- Data for Name: user_role; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5079 (class 0 OID 0)
-- Dependencies: 215
-- Name: department_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.department_id_seq', 1, false);


--
-- TOC entry 5080 (class 0 OID 0)
-- Dependencies: 225
-- Name: dish_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.dish_id_seq', 1, false);


--
-- TOC entry 5081 (class 0 OID 0)
-- Dependencies: 238
-- Name: invalidated_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invalidated_token_id_seq', 1, false);


--
-- TOC entry 5082 (class 0 OID 0)
-- Dependencies: 227
-- Name: menu_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.menu_id_seq', 1, false);


--
-- TOC entry 5083 (class 0 OID 0)
-- Dependencies: 236
-- Name: notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notification_id_seq', 1, false);


--
-- TOC entry 5084 (class 0 OID 0)
-- Dependencies: 230
-- Name: order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_id_seq', 1, false);


--
-- TOC entry 5085 (class 0 OID 0)
-- Dependencies: 219
-- Name: permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.permission_id_seq', 1, false);


--
-- TOC entry 5086 (class 0 OID 0)
-- Dependencies: 234
-- Name: rating_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rating_id_seq', 1, false);


--
-- TOC entry 5087 (class 0 OID 0)
-- Dependencies: 240
-- Name: refresh_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.refresh_token_id_seq', 1, false);


--
-- TOC entry 5088 (class 0 OID 0)
-- Dependencies: 217
-- Name: role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.role_id_seq', 1, false);


--
-- TOC entry 5089 (class 0 OID 0)
-- Dependencies: 232
-- Name: ticket_exchange_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ticket_exchange_id_seq', 1, false);


--
-- TOC entry 5090 (class 0 OID 0)
-- Dependencies: 221
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_id_seq', 1, false);


--
-- TOC entry 4816 (class 2606 OID 16496)
-- Name: department department_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT department_code_key UNIQUE (code);


--
-- TOC entry 4818 (class 2606 OID 16494)
-- Name: department department_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT department_pkey PRIMARY KEY (id);


--
-- TOC entry 4842 (class 2606 OID 16575)
-- Name: dish dish_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dish
    ADD CONSTRAINT dish_pkey PRIMARY KEY (id);


--
-- TOC entry 4866 (class 2606 OID 16696)
-- Name: invalidated_token invalidated_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invalidated_token
    ADD CONSTRAINT invalidated_token_pkey PRIMARY KEY (id);


--
-- TOC entry 4868 (class 2606 OID 16698)
-- Name: invalidated_token invalidated_token_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invalidated_token
    ADD CONSTRAINT invalidated_token_token_key UNIQUE (token);


--
-- TOC entry 4848 (class 2606 OID 16595)
-- Name: menu_dish menu_dish_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu_dish
    ADD CONSTRAINT menu_dish_pkey PRIMARY KEY (menu_id, dish_id);


--
-- TOC entry 4844 (class 2606 OID 16585)
-- Name: menu menu_menu_date_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT menu_menu_date_key UNIQUE (menu_date);


--
-- TOC entry 4846 (class 2606 OID 16583)
-- Name: menu menu_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT menu_pkey PRIMARY KEY (id);


--
-- TOC entry 4864 (class 2606 OID 16682)
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- TOC entry 4852 (class 2606 OID 16613)
-- Name: order order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT order_pkey PRIMARY KEY (id);


--
-- TOC entry 4824 (class 2606 OID 16512)
-- Name: permission permission_action_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT permission_action_key UNIQUE (action);


--
-- TOC entry 4826 (class 2606 OID 16510)
-- Name: permission permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4861 (class 2606 OID 16662)
-- Name: rating rating_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rating
    ADD CONSTRAINT rating_pkey PRIMARY KEY (id);


--
-- TOC entry 4870 (class 2606 OID 16706)
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- TOC entry 4872 (class 2606 OID 16710)
-- Name: refresh_token refresh_token_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_token_key UNIQUE (token);


--
-- TOC entry 4874 (class 2606 OID 16708)
-- Name: refresh_token refresh_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_user_id_key UNIQUE (user_id);


--
-- TOC entry 4820 (class 2606 OID 16504)
-- Name: role role_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_code_key UNIQUE (code);


--
-- TOC entry 4840 (class 2606 OID 16556)
-- Name: role_permission role_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT role_permission_pkey PRIMARY KEY (role_id, permission_id);


--
-- TOC entry 4822 (class 2606 OID 16502)
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- TOC entry 4857 (class 2606 OID 16641)
-- Name: ticket_exchange ticket_exchange_order_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_exchange
    ADD CONSTRAINT ticket_exchange_order_id_key UNIQUE (order_id);


--
-- TOC entry 4859 (class 2606 OID 16639)
-- Name: ticket_exchange ticket_exchange_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_exchange
    ADD CONSTRAINT ticket_exchange_pkey PRIMARY KEY (id);


--
-- TOC entry 4854 (class 2606 OID 16615)
-- Name: order unique_user_menu; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT unique_user_menu UNIQUE (user_id, menu_id);


--
-- TOC entry 4830 (class 2606 OID 16529)
-- Name: user user_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_email_key UNIQUE (email);


--
-- TOC entry 4832 (class 2606 OID 16527)
-- Name: user user_employee_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_employee_code_key UNIQUE (employee_code);


--
-- TOC entry 4834 (class 2606 OID 16523)
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- TOC entry 4838 (class 2606 OID 16541)
-- Name: user_role user_role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT user_role_pkey PRIMARY KEY (user_id, role_id);


--
-- TOC entry 4836 (class 2606 OID 16525)
-- Name: user user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_username_key UNIQUE (username);


--
-- TOC entry 4862 (class 1259 OID 16688)
-- Name: idx_notification_user_read; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_notification_user_read ON public.notification USING btree (user_id, is_read);


--
-- TOC entry 4849 (class 1259 OID 16632)
-- Name: idx_order_menu; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_menu ON public."order" USING btree (menu_id);


--
-- TOC entry 4850 (class 1259 OID 16631)
-- Name: idx_order_user_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_user_status ON public."order" USING btree (user_id, status);


--
-- TOC entry 4855 (class 1259 OID 16652)
-- Name: idx_ticket_exchange_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ticket_exchange_status ON public.ticket_exchange USING btree (status) WHERE ((status)::text = 'OPEN'::text);


--
-- TOC entry 4827 (class 1259 OID 16536)
-- Name: idx_user_department; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_department ON public."user" USING btree (department_id);


--
-- TOC entry 4828 (class 1259 OID 16535)
-- Name: idx_user_full_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_full_name ON public."user" USING btree (full_name);


--
-- TOC entry 4875 (class 2606 OID 16717)
-- Name: department fk_department_created_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT fk_department_created_by FOREIGN KEY (created_by) REFERENCES public."user"(id);


--
-- TOC entry 4876 (class 2606 OID 16722)
-- Name: department fk_department_updated_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT fk_department_updated_by FOREIGN KEY (updated_by) REFERENCES public."user"(id);


--
-- TOC entry 4888 (class 2606 OID 16727)
-- Name: dish fk_dish_created_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dish
    ADD CONSTRAINT fk_dish_created_by FOREIGN KEY (created_by) REFERENCES public."user"(id);


--
-- TOC entry 4889 (class 2606 OID 16732)
-- Name: dish fk_dish_updated_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dish
    ADD CONSTRAINT fk_dish_updated_by FOREIGN KEY (updated_by) REFERENCES public."user"(id);


--
-- TOC entry 4898 (class 2606 OID 16647)
-- Name: ticket_exchange fk_exchange_buyer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_exchange
    ADD CONSTRAINT fk_exchange_buyer FOREIGN KEY (buyer_id) REFERENCES public."user"(id);


--
-- TOC entry 4899 (class 2606 OID 16642)
-- Name: ticket_exchange fk_exchange_order; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_exchange
    ADD CONSTRAINT fk_exchange_order FOREIGN KEY (order_id) REFERENCES public."order"(id);


--
-- TOC entry 4892 (class 2606 OID 16601)
-- Name: menu_dish fk_menu_dish_dish; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu_dish
    ADD CONSTRAINT fk_menu_dish_dish FOREIGN KEY (dish_id) REFERENCES public.dish(id) ON DELETE CASCADE;


--
-- TOC entry 4893 (class 2606 OID 16596)
-- Name: menu_dish fk_menu_dish_menu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu_dish
    ADD CONSTRAINT fk_menu_dish_menu FOREIGN KEY (menu_id) REFERENCES public.menu(id) ON DELETE CASCADE;


--
-- TOC entry 4890 (class 2606 OID 16737)
-- Name: menu fk_menu_updated_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT fk_menu_updated_by FOREIGN KEY (updated_by) REFERENCES public."user"(id);


--
-- TOC entry 4891 (class 2606 OID 16586)
-- Name: menu fk_menu_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT fk_menu_user FOREIGN KEY (created_by) REFERENCES public."user"(id);


--
-- TOC entry 4902 (class 2606 OID 16683)
-- Name: notification fk_notification_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- TOC entry 4894 (class 2606 OID 16621)
-- Name: order fk_order_menu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT fk_order_menu FOREIGN KEY (menu_id) REFERENCES public.menu(id);


--
-- TOC entry 4895 (class 2606 OID 16626)
-- Name: order fk_order_original_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT fk_order_original_user FOREIGN KEY (original_user_id) REFERENCES public."user"(id);


--
-- TOC entry 4896 (class 2606 OID 16772)
-- Name: order fk_order_updated_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT fk_order_updated_by FOREIGN KEY (updated_by) REFERENCES public."user"(id);


--
-- TOC entry 4897 (class 2606 OID 16616)
-- Name: order fk_order_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- TOC entry 4879 (class 2606 OID 16742)
-- Name: permission fk_permission_created_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT fk_permission_created_by FOREIGN KEY (created_by) REFERENCES public."user"(id);


--
-- TOC entry 4880 (class 2606 OID 16747)
-- Name: permission fk_permission_updated_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT fk_permission_updated_by FOREIGN KEY (updated_by) REFERENCES public."user"(id);


--
-- TOC entry 4900 (class 2606 OID 16668)
-- Name: rating fk_rating_menu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rating
    ADD CONSTRAINT fk_rating_menu FOREIGN KEY (menu_id) REFERENCES public.menu(id);


--
-- TOC entry 4901 (class 2606 OID 16663)
-- Name: rating fk_rating_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rating
    ADD CONSTRAINT fk_rating_user FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- TOC entry 4903 (class 2606 OID 16711)
-- Name: refresh_token fk_refresh_token_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- TOC entry 4877 (class 2606 OID 16752)
-- Name: role fk_role_created_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT fk_role_created_by FOREIGN KEY (created_by) REFERENCES public."user"(id);


--
-- TOC entry 4886 (class 2606 OID 16562)
-- Name: role_permission fk_role_permission_permission; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id) REFERENCES public.permission(id) ON DELETE CASCADE;


--
-- TOC entry 4887 (class 2606 OID 16557)
-- Name: role_permission fk_role_permission_role; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES public.role(id) ON DELETE CASCADE;


--
-- TOC entry 4878 (class 2606 OID 16757)
-- Name: role fk_role_updated_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT fk_role_updated_by FOREIGN KEY (updated_by) REFERENCES public."user"(id);


--
-- TOC entry 4881 (class 2606 OID 16762)
-- Name: user fk_user_created_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT fk_user_created_by FOREIGN KEY (created_by) REFERENCES public."user"(id);


--
-- TOC entry 4882 (class 2606 OID 16530)
-- Name: user fk_user_department; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT fk_user_department FOREIGN KEY (department_id) REFERENCES public.department(id);


--
-- TOC entry 4884 (class 2606 OID 16547)
-- Name: user_role fk_user_role_role; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES public.role(id) ON DELETE CASCADE;


--
-- TOC entry 4885 (class 2606 OID 16542)
-- Name: user_role fk_user_role_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- TOC entry 4883 (class 2606 OID 16767)
-- Name: user fk_user_updated_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT fk_user_updated_by FOREIGN KEY (updated_by) REFERENCES public."user"(id);


-- Completed on 2026-06-25 16:05:44

--
-- PostgreSQL database dump complete
--

\unrestrict GrKPmnWU0Fzd7QSncVBZFEMghdvRtUbwoSy0m4uu4f4YnZVZwDaTv5HNBAajC1e

