--
-- PostgreSQL database dump
--

\restrict YOwKeJtbxao9DuSEfsKzIoNUODUH113j424aTsEH9Og6Qpg3ARoEgFRArKswoEm

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

-- Started on 2026-07-16 08:57:48

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 248 (class 1255 OID 16799)
-- Name: update_updated_at_column(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.update_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.update_updated_at_column() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 243 (class 1259 OID 16851)
-- Name: audit_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    user_id bigint,
    action character varying(255) NOT NULL,
    target_entity character varying(100),
    target_id bigint,
    old_value text,
    new_value text,
    ip_address character varying(50),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.audit_log OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 16850)
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16490)
-- Name: department; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.department (
    id bigint NOT NULL,
    code character varying(50),
    name character varying(255),
    created_by bigint,
    updated_by bigint,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.department OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16489)
-- Name: department_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16568)
-- Name: dish; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dish (
    id bigint NOT NULL,
    name character varying(255),
    is_active boolean DEFAULT true,
    created_by bigint,
    updated_by bigint,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    description text,
    type character varying(255)
);


ALTER TABLE public.dish OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16567)
-- Name: dish_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dish ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dish_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16690)
-- Name: invalidated_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invalidated_token (
    id bigint NOT NULL,
    token character varying(500),
    expiry_time timestamp with time zone
);


ALTER TABLE public.invalidated_token OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16689)
-- Name: invalidated_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invalidated_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invalidated_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16577)
-- Name: menu; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.menu (
    id bigint NOT NULL,
    menu_date date,
    status character varying(20),
    created_by bigint,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    price_id bigint,
    image_url character varying(1024),
    name character varying(255),
    type character varying(20) DEFAULT 'LIST'::character varying NOT NULL
);


ALTER TABLE public.menu OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16591)
-- Name: menu_dish; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.menu_dish (
    menu_id bigint NOT NULL,
    dish_id bigint NOT NULL,
    display_order integer
);


ALTER TABLE public.menu_dish OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16576)
-- Name: menu_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.menu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16674)
-- Name: notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notification (
    id bigint NOT NULL,
    user_id bigint,
    title character varying(255),
    content text,
    is_read boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.notification OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16673)
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16607)
-- Name: order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."order" (
    id bigint NOT NULL,
    user_id bigint,
    menu_id bigint,
    price numeric(10,2),
    status character varying(20),
    ticket_source character varying(20),
    original_user_id bigint,
    is_printed boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    order_date date
);


ALTER TABLE public."order" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16606)
-- Name: order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."order" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 16885)
-- Name: payment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payment (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    amount numeric(10,2) NOT NULL,
    note text,
    paid_at timestamp(6) with time zone,
    payment_method character varying(20) NOT NULL,
    payment_month integer NOT NULL,
    payment_year integer NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.payment OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 16884)
-- Name: payment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16506)
-- Name: permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permission (
    id bigint NOT NULL,
    action character varying(100),
    description character varying(255),
    created_by bigint,
    updated_by bigint,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.permission OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16505)
-- Name: permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 16901)
-- Name: price; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.price (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    created_by bigint,
    updated_at timestamp(6) with time zone,
    updated_by bigint,
    amount numeric(10,2) NOT NULL,
    description character varying(500),
    is_active boolean NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.price OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 16900)
-- Name: price_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.price ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.price_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16700)
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_token (
    id bigint NOT NULL,
    user_id bigint,
    token character varying(500),
    expiry_time timestamp with time zone
);


ALTER TABLE public.refresh_token OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16699)
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16498)
-- Name: role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role (
    id bigint NOT NULL,
    code character varying(50),
    name character varying(255),
    created_by bigint,
    updated_by bigint,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    description character varying(500)
);


ALTER TABLE public.role OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16497)
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16552)
-- Name: role_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role_permission (
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL
);


ALTER TABLE public.role_permission OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 16834)
-- Name: system_config; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.system_config (
    id bigint NOT NULL,
    config_key character varying(100) NOT NULL,
    config_value text,
    description character varying(255),
    updated_by bigint,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.system_config OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 16833)
-- Name: system_config_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.system_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.system_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16634)
-- Name: ticket_exchange; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ticket_exchange (
    id bigint NOT NULL,
    order_id bigint,
    buyer_id bigint,
    status character varying(20),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.ticket_exchange OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16633)
-- Name: ticket_exchange_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ticket_exchange ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_exchange_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16514)
-- Name: user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."user" (
    id bigint NOT NULL,
    username character varying(50),
    full_name character varying(255),
    password character varying(255),
    department_id bigint,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    created_by bigint,
    updated_by bigint
);


ALTER TABLE public."user" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16513)
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16537)
-- Name: user_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_role (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.user_role OWNER TO postgres;

--
-- TOC entry 4904 (class 2606 OID 16858)
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4842 (class 2606 OID 16496)
-- Name: department department_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT department_code_key UNIQUE (code);


--
-- TOC entry 4844 (class 2606 OID 16494)
-- Name: department department_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT department_pkey PRIMARY KEY (id);


--
-- TOC entry 4864 (class 2606 OID 16575)
-- Name: dish dish_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dish
    ADD CONSTRAINT dish_pkey PRIMARY KEY (id);


--
-- TOC entry 4890 (class 2606 OID 16696)
-- Name: invalidated_token invalidated_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invalidated_token
    ADD CONSTRAINT invalidated_token_pkey PRIMARY KEY (id);


--
-- TOC entry 4892 (class 2606 OID 16698)
-- Name: invalidated_token invalidated_token_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invalidated_token
    ADD CONSTRAINT invalidated_token_token_key UNIQUE (token);


--
-- TOC entry 4871 (class 2606 OID 16928)
-- Name: menu_dish menu_dish_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu_dish
    ADD CONSTRAINT menu_dish_pkey PRIMARY KEY (menu_id, dish_id);


--
-- TOC entry 4866 (class 2606 OID 16583)
-- Name: menu menu_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT menu_pkey PRIMARY KEY (id);


--
-- TOC entry 4888 (class 2606 OID 16682)
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- TOC entry 4876 (class 2606 OID 16613)
-- Name: order order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT order_pkey PRIMARY KEY (id);


--
-- TOC entry 4907 (class 2606 OID 16891)
-- Name: payment payment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (id);


--
-- TOC entry 4850 (class 2606 OID 16512)
-- Name: permission permission_action_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT permission_action_key UNIQUE (action);


--
-- TOC entry 4852 (class 2606 OID 16510)
-- Name: permission permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4909 (class 2606 OID 16907)
-- Name: price price_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.price
    ADD CONSTRAINT price_pkey PRIMARY KEY (id);


--
-- TOC entry 4894 (class 2606 OID 16706)
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- TOC entry 4896 (class 2606 OID 16710)
-- Name: refresh_token refresh_token_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_token_key UNIQUE (token);


--
-- TOC entry 4898 (class 2606 OID 16708)
-- Name: refresh_token refresh_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_user_id_key UNIQUE (user_id);


--
-- TOC entry 4846 (class 2606 OID 16504)
-- Name: role role_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_code_key UNIQUE (code);


--
-- TOC entry 4862 (class 2606 OID 16556)
-- Name: role_permission role_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT role_permission_pkey PRIMARY KEY (role_id, permission_id);


--
-- TOC entry 4848 (class 2606 OID 16502)
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- TOC entry 4900 (class 2606 OID 16843)
-- Name: system_config system_config_config_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_config
    ADD CONSTRAINT system_config_config_key_key UNIQUE (config_key);


--
-- TOC entry 4902 (class 2606 OID 16841)
-- Name: system_config system_config_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_config
    ADD CONSTRAINT system_config_pkey PRIMARY KEY (id);


--
-- TOC entry 4883 (class 2606 OID 16641)
-- Name: ticket_exchange ticket_exchange_order_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_exchange
    ADD CONSTRAINT ticket_exchange_order_id_key UNIQUE (order_id);


--
-- TOC entry 4885 (class 2606 OID 16639)
-- Name: ticket_exchange ticket_exchange_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_exchange
    ADD CONSTRAINT ticket_exchange_pkey PRIMARY KEY (id);


--
-- TOC entry 4868 (class 2606 OID 16909)
-- Name: menu unique_menu_date_price; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT unique_menu_date_price UNIQUE (menu_date, price_id);


--
-- TOC entry 4878 (class 2606 OID 16615)
-- Name: order unique_user_menu; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT unique_user_menu UNIQUE (user_id, menu_id);


--
-- TOC entry 4880 (class 2606 OID 16933)
-- Name: order unique_user_order_date; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT unique_user_order_date UNIQUE (user_id, order_date);


--
-- TOC entry 4856 (class 2606 OID 16523)
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- TOC entry 4860 (class 2606 OID 16541)
-- Name: user_role user_role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT user_role_pkey PRIMARY KEY (user_id, role_id);


--
-- TOC entry 4858 (class 2606 OID 16525)
-- Name: user user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_username_key UNIQUE (username);


--
-- TOC entry 4886 (class 1259 OID 16688)
-- Name: idx_notification_user_read; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_notification_user_read ON public.notification USING btree (user_id, is_read);


--
-- TOC entry 4872 (class 1259 OID 16632)
-- Name: idx_order_menu; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_menu ON public."order" USING btree (menu_id);


--
-- TOC entry 4873 (class 1259 OID 16899)
-- Name: idx_order_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_status ON public."order" USING btree (status);


--
-- TOC entry 4874 (class 1259 OID 16631)
-- Name: idx_order_user_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_user_status ON public."order" USING btree (user_id, status);


--
-- TOC entry 4905 (class 1259 OID 16898)
-- Name: idx_payment_user_month_year; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_payment_user_month_year ON public.payment USING btree (user_id, payment_year, payment_month);


--
-- TOC entry 4881 (class 1259 OID 16652)
-- Name: idx_ticket_exchange_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ticket_exchange_status ON public.ticket_exchange USING btree (status) WHERE ((status)::text = 'OPEN'::text);


--
-- TOC entry 4853 (class 1259 OID 16536)
-- Name: idx_user_department; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_department ON public."user" USING btree (department_id);


--
-- TOC entry 4854 (class 1259 OID 16535)
-- Name: idx_user_full_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_full_name ON public."user" USING btree (full_name);


--
-- TOC entry 4869 (class 1259 OID 16945)
-- Name: uq_menu_image_week; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_menu_image_week ON public.menu USING btree (menu_date) WHERE ((type)::text = 'IMAGE'::text);


--
-- TOC entry 4941 (class 2620 OID 16825)
-- Name: department update_department_modtime; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_department_modtime BEFORE UPDATE ON public.department FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- TOC entry 4944 (class 2620 OID 16826)
-- Name: dish update_dish_modtime; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_dish_modtime BEFORE UPDATE ON public.dish FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- TOC entry 4945 (class 2620 OID 16827)
-- Name: menu update_menu_modtime; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_menu_modtime BEFORE UPDATE ON public.menu FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- TOC entry 4946 (class 2620 OID 16828)
-- Name: order update_order_modtime; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_order_modtime BEFORE UPDATE ON public."order" FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- TOC entry 4943 (class 2620 OID 16830)
-- Name: permission update_permission_modtime; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_permission_modtime BEFORE UPDATE ON public.permission FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- TOC entry 4942 (class 2620 OID 16829)
-- Name: role update_role_modtime; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_role_modtime BEFORE UPDATE ON public.role FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- TOC entry 4947 (class 2620 OID 16849)
-- Name: system_config update_system_config_modtime; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_system_config_modtime BEFORE UPDATE ON public.system_config FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- TOC entry 4939 (class 2606 OID 16859)
-- Name: audit_log audit_log_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- TOC entry 4910 (class 2606 OID 16717)
-- Name: department fk_department_created_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT fk_department_created_by FOREIGN KEY (created_by) REFERENCES public."user"(id);


--
-- TOC entry 4911 (class 2606 OID 16722)
-- Name: department fk_department_updated_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT fk_department_updated_by FOREIGN KEY (updated_by) REFERENCES public."user"(id);


--
-- TOC entry 4923 (class 2606 OID 16727)
-- Name: dish fk_dish_created_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dish
    ADD CONSTRAINT fk_dish_created_by FOREIGN KEY (created_by) REFERENCES public."user"(id);


--
-- TOC entry 4924 (class 2606 OID 16732)
-- Name: dish fk_dish_updated_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dish
    ADD CONSTRAINT fk_dish_updated_by FOREIGN KEY (updated_by) REFERENCES public."user"(id);


--
-- TOC entry 4934 (class 2606 OID 16647)
-- Name: ticket_exchange fk_exchange_buyer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_exchange
    ADD CONSTRAINT fk_exchange_buyer FOREIGN KEY (buyer_id) REFERENCES public."user"(id);


--
-- TOC entry 4935 (class 2606 OID 16642)
-- Name: ticket_exchange fk_exchange_order; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_exchange
    ADD CONSTRAINT fk_exchange_order FOREIGN KEY (order_id) REFERENCES public."order"(id);


--
-- TOC entry 4928 (class 2606 OID 16601)
-- Name: menu_dish fk_menu_dish_dish; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu_dish
    ADD CONSTRAINT fk_menu_dish_dish FOREIGN KEY (dish_id) REFERENCES public.dish(id) ON DELETE CASCADE;


--
-- TOC entry 4929 (class 2606 OID 16596)
-- Name: menu_dish fk_menu_dish_menu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu_dish
    ADD CONSTRAINT fk_menu_dish_menu FOREIGN KEY (menu_id) REFERENCES public.menu(id) ON DELETE CASCADE;


--
-- TOC entry 4925 (class 2606 OID 16737)
-- Name: menu fk_menu_updated_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT fk_menu_updated_by FOREIGN KEY (updated_by) REFERENCES public."user"(id);


--
-- TOC entry 4926 (class 2606 OID 16586)
-- Name: menu fk_menu_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT fk_menu_user FOREIGN KEY (created_by) REFERENCES public."user"(id);


--
-- TOC entry 4936 (class 2606 OID 16683)
-- Name: notification fk_notification_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- TOC entry 4930 (class 2606 OID 16621)
-- Name: order fk_order_menu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT fk_order_menu FOREIGN KEY (menu_id) REFERENCES public.menu(id);


--
-- TOC entry 4931 (class 2606 OID 16626)
-- Name: order fk_order_original_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT fk_order_original_user FOREIGN KEY (original_user_id) REFERENCES public."user"(id);


--
-- TOC entry 4932 (class 2606 OID 16772)
-- Name: order fk_order_updated_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT fk_order_updated_by FOREIGN KEY (updated_by) REFERENCES public."user"(id);


--
-- TOC entry 4933 (class 2606 OID 16616)
-- Name: order fk_order_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- TOC entry 4914 (class 2606 OID 16742)
-- Name: permission fk_permission_created_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT fk_permission_created_by FOREIGN KEY (created_by) REFERENCES public."user"(id);


--
-- TOC entry 4915 (class 2606 OID 16747)
-- Name: permission fk_permission_updated_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT fk_permission_updated_by FOREIGN KEY (updated_by) REFERENCES public."user"(id);


--
-- TOC entry 4937 (class 2606 OID 16711)
-- Name: refresh_token fk_refresh_token_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- TOC entry 4912 (class 2606 OID 16752)
-- Name: role fk_role_created_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT fk_role_created_by FOREIGN KEY (created_by) REFERENCES public."user"(id);


--
-- TOC entry 4921 (class 2606 OID 16562)
-- Name: role_permission fk_role_permission_permission; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id) REFERENCES public.permission(id) ON DELETE CASCADE;


--
-- TOC entry 4922 (class 2606 OID 16557)
-- Name: role_permission fk_role_permission_role; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES public.role(id) ON DELETE CASCADE;


--
-- TOC entry 4913 (class 2606 OID 16757)
-- Name: role fk_role_updated_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT fk_role_updated_by FOREIGN KEY (updated_by) REFERENCES public."user"(id);


--
-- TOC entry 4916 (class 2606 OID 16762)
-- Name: user fk_user_created_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT fk_user_created_by FOREIGN KEY (created_by) REFERENCES public."user"(id);


--
-- TOC entry 4917 (class 2606 OID 16530)
-- Name: user fk_user_department; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT fk_user_department FOREIGN KEY (department_id) REFERENCES public.department(id);


--
-- TOC entry 4919 (class 2606 OID 16547)
-- Name: user_role fk_user_role_role; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES public.role(id) ON DELETE CASCADE;


--
-- TOC entry 4920 (class 2606 OID 16542)
-- Name: user_role fk_user_role_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- TOC entry 4918 (class 2606 OID 16767)
-- Name: user fk_user_updated_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT fk_user_updated_by FOREIGN KEY (updated_by) REFERENCES public."user"(id);


--
-- TOC entry 4940 (class 2606 OID 16892)
-- Name: payment fkcp0yo0h2iv9p04x3ydel5ymjs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT fkcp0yo0h2iv9p04x3ydel5ymjs FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- TOC entry 4927 (class 2606 OID 16910)
-- Name: menu fki1jwmnelm6en1e4ysce8klyej; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT fki1jwmnelm6en1e4ysce8klyej FOREIGN KEY (price_id) REFERENCES public.price(id);


--
-- TOC entry 4938 (class 2606 OID 16844)
-- Name: system_config system_config_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_config
    ADD CONSTRAINT system_config_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public."user"(id);


-- Completed on 2026-07-16 08:57:48

--
-- PostgreSQL database dump complete
--

\unrestrict YOwKeJtbxao9DuSEfsKzIoNUODUH113j424aTsEH9Og6Qpg3ARoEgFRArKswoEm

